# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6843ab16e0da9d9b563065c22b06b0cd2d6fec7564f53160af21a5e00018efc7c2713ec622de85334f6fb704263fa6a97fc74a01318285421acec4e542b2f5f9

test:
  secret_key_base: fafb9a52e2978d4e74ebc50866402771c07df25fb148a4856558cb17bc08694b1d1296ba2b73896d39b6a546c094ef30452ef9e5372128611a764903a13180db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
